import enum

class PlayerStatus(enum.Enum):
    """
    Represents the current status of a player character.
    """
    UNKNOWN = "unknown"            # Default or error state
    IDLE = "idle"                  # Player is in a safe area, not actively doing much
    EXPLORING = "exploring"        # Player is actively moving around, looking for content, default active state
    COMBAT = "combat"              # Player is engaged in combat
    DIALOGUE = "dialogue"          # Player is in a conversation with an NPC
    TRADING = "trading"            # Player is interacting with a shop or another player for trade
    MENU = "menu"                  # Player is interacting with a game menu (e.g., inventory, stats)
    AWAY = "away"                  # Player is AFK or otherwise temporarily inactive
    DEAD = "dead"                  # Player character is incapacitated
    AWAITING_MODERATION = "awaiting_moderation" # Player action requires GM approval
    TURN_ENDED_PENDING_RESOLUTION = "turn_ended_pending_resolution" # Player has submitted turn, waiting for guild-wide processing
    PROCESSING_GUILD_TURN = "processing_guild_turn" # Player's actions are part of active guild turn processing
<<<<<<< HEAD
=======
    PROCESSING_ACTION = "processing_action"  # Player's individual action is being processed
>>>>>>> b2afaca2eb51d4d05c43280db1641e28092719fc

class PartyTurnStatus(enum.Enum):
    """
    Represents the current turn status of a party in turn-based gameplay.
    """
    UNKNOWN = "unknown"            # Default or error state
    IDLE = "idle"                  # Party is not in active turn-based gameplay (e.g., exploring together)
    AWAITING_PARTY_ACTION = "awaiting_party_action" # Party's turn, members deciding or leader to submit /end_party_turn
    TURN_ENDED_PENDING_RESOLUTION = "turn_ended_pending_resolution" # Party has submitted turn, waiting for guild-wide processing
    PROCESSING_GUILD_TURN = "processing_guild_turn" # Party's actions are part of active guild turn processing
    AWAITING_MODERATION = "awaiting_moderation" # Party actions/turn outcome requires GM approval (can be a sub-state or parallel)

class OwnerEntityType(enum.Enum):
    """
    Represents the type of entity that can own an inventory.
    """
    PLAYER = "player"
    GENERATED_NPC = "generated_npc"
    PARTY = "party" # For shared party inventory
    LOCATION_CONTAINER = "location_container" # E.g. a chest in a location
    # Add more types as needed, e.g., specific NPC types if they have separate table

class EventType(enum.Enum):
    """
    Represents the type of event that can be logged in the StoryLog.
    """
    PLAYER_ACTION = "player_action"         # A general action taken by a player
    NPC_ACTION = "npc_action"               # A general action taken by an NPC
    SYSTEM_EVENT = "system_event"           # Events generated by the game system (e.g., weather change)
    COMBAT_START = "combat_start"
    COMBAT_ACTION = "combat_action"         # Specific action within combat (attack, defend, ability use)
    COMBAT_END = "combat_end"
    MOVEMENT = "movement"                   # Player or NPC moved to a new location
    DIALOGUE_START = "dialogue_start"
    DIALOGUE_LINE = "dialogue_line"         # A line of dialogue spoken
    DIALOGUE_END = "dialogue_end"
    QUEST_ACCEPTED = "quest_accepted"
    QUEST_STEP_COMPLETED = "quest_step_completed"
    QUEST_COMPLETED = "quest_completed"
    QUEST_FAILED = "quest_failed"
    ITEM_ACQUIRED = "item_acquired"
    ITEM_USED = "item_used"
    ITEM_DROPPED = "item_dropped"
    TRADE_INITIATED = "trade_initiated"
    TRADE_COMPLETED = "trade_completed"
    LEVEL_UP = "level_up"
    XP_GAINED = "xp_gained"
    RELATIONSHIP_CHANGE = "relationship_change"
    FACTION_CHANGE = "faction_change"       # Change in faction standing or membership
    WORLD_STATE_CHANGE = "world_state_change" # Significant change in the game world
    MASTER_COMMAND = "master_command"       # An action taken by a Game Master
    ERROR_EVENT = "error_event"             # For logging internal errors if necessary
    # Add more specific event types as the game mechanics are developed

class RelationshipEntityType(enum.Enum):
    """
    Represents the types of entities that can be part of a relationship.
    """
    PLAYER = "player"
    PARTY = "party"
    GENERATED_NPC = "generated_npc"
    GENERATED_FACTION = "generated_faction"
    # Consider if specific NPC types or other global entities need to be here

class QuestStatus(enum.Enum):
    """
    Represents the status of a player's progress on a quest.
    """
    NOT_STARTED = "not_started"    # Quest is available but not yet accepted by the player
    ACTIVE = "active"              # Player has accepted the quest and is working on it
    COMPLETED = "completed"        # Player has successfully finished all steps of the quest
    FAILED = "failed"              # Player has failed the quest
    ABANDONED = "abandoned"        # Player chose to abandon the quest
    # Add more statuses as needed, e.g., AWAITING_TURN_IN

# Example of how these might be used in a model:
# from sqlalchemy import Enum as SQLAlchemyEnum
# from sqlalchemy.orm import Mapped, mapped_column
# from .base import Base # Assuming Base is your declarative base
#
# class Player(Base):
#     __tablename__ = "players"
#     # ... other columns
#     status: Mapped[PlayerStatus] = mapped_column(SQLAlchemyEnum(PlayerStatus), default=PlayerStatus.IDLE)

# class Party(Base):
#     __tablename__ = "parties"
#     # ... other columns
#     turn_status: Mapped[PartyTurnStatus] = mapped_column(SQLAlchemyEnum(PartyTurnStatus), default=PartyTurnStatus.IDLE)

class ModerationStatus(enum.Enum):
    """
    Represents the moderation status of AI-generated content.
    """
    PENDING_MODERATION = "pending_moderation"
    APPROVED = "approved"
    REJECTED = "rejected"
    EDITED_PENDING_APPROVAL = "edited_pending_approval" # After a master edits it, needs re-approval
    VALIDATION_FAILED = "validation_failed" # Automated parsing/validation failed
    SAVED = "saved" # Successfully saved to game entities
    ERROR_ON_SAVE = "error_on_save" # An error occurred during the save_approved_generation step

class ConflictStatus(enum.Enum):
    """
    Represents the status of a pending conflict requiring resolution.
    """
    PENDING_MASTER_RESOLUTION = "pending_master_resolution" # Awaiting Game Master intervention
    RESOLVED_AUTOMATICALLY_CONTINUE = "resolved_automatically_continue" # Auto-resolved, action can proceed
    RESOLVED_AUTOMATICALLY_REJECT = "resolved_automatically_reject"   # Auto-resolved, action is rejected/failed
    RESOLVED_BY_MASTER_APPROVED = "resolved_by_master_approved"   # Master approved (possibly with edits)
    RESOLVED_BY_MASTER_REJECTED = "resolved_by_master_rejected"   # Master rejected the action(s)
    EXPIRED = "expired"                                     # Conflict resolution timed out (future use)

import logging
logger = logging.getLogger(__name__)
logger.info("Game-specific Enums (PlayerStatus, PartyTurnStatus, OwnerEntityType, ModerationStatus, ConflictStatus, etc.) defined.")
