"""Create rule_configs table

Revision ID: 0002
Revises: 0001
Create Date: YYYY-MM-DD HH:MM:SS.SSSSSS

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = 'init_0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_configs_guild_id'), 'rule_configs', ['guild_id'], unique=False)
    op.create_index(op.f('ix_rule_configs_id'), 'rule_configs', ['id'], unique=False)
    op.create_index(op.f('ix_rule_configs_key'), 'rule_configs', ['key'], unique=False)
    op.create_index('ix_rule_configs_guild_id_key', 'rule_configs', ['guild_id', 'key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rule_configs_guild_id_key', table_name='rule_configs')
    op.drop_index(op.f('ix_rule_configs_key'), table_name='rule_configs')
    op.drop_index(op.f('ix_rule_configs_id'), table_name='rule_configs')
    op.drop_index(op.f('ix_rule_configs_guild_id'), table_name='rule_configs')
    op.drop_table('rule_configs')
    # ### end Alembic commands ###
