"""create_abilities_table

Revision ID: 0003
Revises: 0002
Create Date: YYYY-MM-DD HH:MM:SS.MS # Будет заменено актуальной датой при выполнении

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('static_id', sa.Text(), nullable=False),
    sa.Column('name_i18n', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('description_i18n', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('properties_json', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.id'], name=op.f('fk_abilities_guild_id_guild_configs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abilities')),
    sa.UniqueConstraint('guild_id', 'static_id', name=op.f('uq_ability_guild_static_id'))
    )
    op.create_index(op.f('ix_abilities_guild_id'), 'abilities', ['guild_id'], unique=False)
    op.create_index(op.f('ix_abilities_id'), 'abilities', ['id'], unique=False)
    op.create_index(op.f('ix_abilities_static_id'), 'abilities', ['static_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_abilities_static_id'), table_name='abilities')
    op.drop_index(op.f('ix_abilities_id'), table_name='abilities')
    op.drop_index(op.f('ix_abilities_guild_id'), table_name='abilities')
    op.drop_table('abilities')
    # ### end Alembic commands ###
