"""add current_sublocation_name to player

Revision ID: 0008_add_player_sublocation
Revises: 4a069d44a15c
Create Date: YYYY-MM-DD HH:MM:SS.SSSSSS # Will be replaced by current timestamp

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0008_add_player_sublocation'
down_revision: Union[str, None] = '4a069d44a15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('current_sublocation_name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'current_sublocation_name')
    # ### end Alembic commands ###
