"""update ability model guild_id nullable and add type

Revision ID: 202407181205
Revises: 202407181200
Create Date: 2024-07-18 12:05:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202407181205'
down_revision: Union[str, None] = '202407181200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.Text(), nullable=True))
        batch_op.alter_column('guild_id',
               existing_type=sa.BIGINT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_abilities_type'), ['type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abilities_type'))
        batch_op.alter_column('guild_id',
               existing_type=sa.BIGINT(),
               nullable=False)
        batch_op.drop_column('type')

    # ### end Alembic commands ###
