"""Add global entities models

Revision ID: a1b2c3d4e5f6
Revises: e221edc41551
Create Date: 2024-07-15 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# sqlalchemy.dialects.postgresql import JSONB # Removed as direct import, using sa.JSON


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = 'e221edc41551' # Placeholder, may need adjustment
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_npcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('static_id', sa.String(), nullable=False),
    sa.Column('name_i18n', sa.JSON(), nullable=False),
    sa.Column('description_i18n', sa.JSON(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('base_npc_id', sa.Integer(), nullable=True),
    sa.Column('properties_json', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_npc_id'], ['generated_npcs.id'], name=op.f('fk_global_npcs_base_npc_id_generated_npcs')),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], name=op.f('fk_global_npcs_current_location_id_locations')),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.id'], name=op.f('fk_global_npcs_guild_id_guild_configs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_npcs'))
    )
    op.create_index(op.f('ix_global_npcs_current_location_id'), 'global_npcs', ['current_location_id'], unique=False)
    op.create_index(op.f('ix_global_npcs_guild_id'), 'global_npcs', ['guild_id'], unique=False)
    op.create_index('ix_global_npcs_guild_id_static_id', 'global_npcs', ['guild_id', 'static_id'], unique=True)
    op.create_index(op.f('ix_global_npcs_id'), 'global_npcs', ['id'], unique=False)
    op.create_index(op.f('ix_global_npcs_static_id'), 'global_npcs', ['static_id'], unique=False)

    op.create_table('mobile_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('static_id', sa.String(), nullable=False),
    sa.Column('name_i18n', sa.JSON(), nullable=False),
    sa.Column('description_i18n', sa.JSON(), nullable=True),
    sa.Column('current_location_id', sa.Integer(), nullable=True),
    sa.Column('leader_global_npc_id', sa.Integer(), nullable=True),
    sa.Column('members_definition_json', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    sa.Column('properties_json', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_location_id'], ['locations.id'], name=op.f('fk_mobile_groups_current_location_id_locations')),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.id'], name=op.f('fk_mobile_groups_guild_id_guild_configs')),
    sa.ForeignKeyConstraint(['leader_global_npc_id'], ['global_npcs.id'], name=op.f('fk_mobile_groups_leader_global_npc_id_global_npcs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mobile_groups'))
    )
    op.create_index(op.f('ix_mobile_groups_current_location_id'), 'mobile_groups', ['current_location_id'], unique=False)
    op.create_index(op.f('ix_mobile_groups_guild_id'), 'mobile_groups', ['guild_id'], unique=False)
    op.create_index('ix_mobile_groups_guild_id_static_id', 'mobile_groups', ['guild_id', 'static_id'], unique=True)
    op.create_index(op.f('ix_mobile_groups_id'), 'mobile_groups', ['id'], unique=False)
    op.create_index(op.f('ix_mobile_groups_static_id'), 'mobile_groups', ['static_id'], unique=False)

    op.create_table('global_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('static_id', sa.String(), nullable=False),
    sa.Column('name_i18n', sa.JSON(), nullable=False),
    sa.Column('description_i18n', sa.JSON(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('trigger_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expiration_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False, server_default='pending'),
    sa.Column('properties_json', sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id'], ['guild_configs.id'], name=op.f('fk_global_events_guild_id_guild_configs')),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_global_events_location_id_locations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_global_events'))
    )
    op.create_index(op.f('ix_global_events_event_type'), 'global_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_global_events_guild_id'), 'global_events', ['guild_id'], unique=False)
    op.create_index('ix_global_events_guild_id_static_id', 'global_events', ['guild_id', 'static_id'], unique=True)
    op.create_index(op.f('ix_global_events_id'), 'global_events', ['id'], unique=False)
    op.create_index(op.f('ix_global_events_location_id'), 'global_events', ['location_id'], unique=False)
    op.create_index(op.f('ix_global_events_static_id'), 'global_events', ['static_id'], unique=False)
    op.create_index(op.f('ix_global_events_status'), 'global_events', ['status'], unique=False)
    op.create_index('ix_global_events_status_trigger_time', 'global_events', ['status', 'trigger_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_global_events_status_trigger_time', table_name='global_events')
    op.drop_index(op.f('ix_global_events_status'), table_name='global_events')
    op.drop_index(op.f('ix_global_events_static_id'), table_name='global_events')
    op.drop_index(op.f('ix_global_events_location_id'), table_name='global_events')
    op.drop_index(op.f('ix_global_events_id'), table_name='global_events')
    op.drop_index('ix_global_events_guild_id_static_id', table_name='global_events')
    op.drop_index(op.f('ix_global_events_guild_id'), table_name='global_events')
    op.drop_index(op.f('ix_global_events_event_type'), table_name='global_events')
    op.drop_table('global_events')

    op.drop_index(op.f('ix_mobile_groups_static_id'), table_name='mobile_groups')
    op.drop_index(op.f('ix_mobile_groups_id'), table_name='mobile_groups')
    op.drop_index('ix_mobile_groups_guild_id_static_id', table_name='mobile_groups')
    op.drop_index(op.f('ix_mobile_groups_guild_id'), table_name='mobile_groups')
    op.drop_index(op.f('ix_mobile_groups_current_location_id'), table_name='mobile_groups')
    op.drop_table('mobile_groups')

    op.drop_index(op.f('ix_global_npcs_static_id'), table_name='global_npcs')
    op.drop_index(op.f('ix_global_npcs_id'), table_name='global_npcs')
    op.drop_index('ix_global_npcs_guild_id_static_id', table_name='global_npcs')
    op.drop_index(op.f('ix_global_npcs_guild_id'), table_name='global_npcs')
    op.drop_index(op.f('ix_global_npcs_current_location_id'), table_name='global_npcs')
    op.drop_table('global_npcs')
    # ### end Alembic commands ###
