"""update status_effect model guild_id nullable

Revision ID: 202407181210
Revises: 202407181205
Create Date: 2024-07-18 12:10:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '202407181210'
down_revision: Union[str, None] = '202407181205'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_effects', schema=None) as batch_op:
        batch_op.alter_column('guild_id',
               existing_type=sa.BIGINT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_effects', schema=None) as batch_op:
        batch_op.alter_column('guild_id',
               existing_type=sa.BIGINT(),
               nullable=False)

    # ### end Alembic commands ###
