"""add_fields_to_items_and_inventory_items

Revision ID: 768728ada8e2
Revises: e221edc41551
Create Date: 2025-07-06 08:50:54.881952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '768728ada8e2'
down_revision: Union[str, Sequence[str], None] = 'e221edc41551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('equipped_status', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_inventory_items_equipped_status'), ['equipped_status'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slot_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_stackable', sa.Boolean(), nullable=False, server_default=sa.text('true')))
        batch_op.create_index(batch_op.f('ix_items_slot_type'), ['slot_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_slot_type'))
        batch_op.drop_column('is_stackable')
        batch_op.drop_column('slot_type')

    with op.batch_alter_table('inventory_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_items_equipped_status'))
        batch_op.drop_column('equipped_status')
    # ### end Alembic commands ###
