"""Initial full state

Revision ID: c3a08c4dbe7e
<<<<<<< HEAD
Revises: 
=======
Revises:
>>>>>>> 3648882d7ce127ff9cdbdd88b7ec75d55362e395
Create Date: 2025-07-06 20:33:01.254259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a08c4dbe7e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
