"""create_master_users_table

Revision ID: cdc86ea77142
Revises: 711257a22d1d
Create Date: 2025-07-10 12:24:56.661223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc86ea77142'
down_revision: Union[str, Sequence[str], None] = '711257a22d1d' # Это ID последней миграции из AGENTS.md (Task 52)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('discord_user_id', sa.String(), nullable=False),
    sa.Column('discord_username', sa.String(), nullable=False),
    sa.Column('discord_avatar_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_users'))
    )
    op.create_index(op.f('ix_master_users_discord_user_id'), 'master_users', ['discord_user_id'], unique=True)
    op.create_index(op.f('ix_master_users_id'), 'master_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_master_users_id'), table_name='master_users')
    op.drop_index(op.f('ix_master_users_discord_user_id'), table_name='master_users')
    op.drop_table('master_users')
    # ### end Alembic commands ###
