"""create_guild_configs_table

Revision ID: init_0001
Revises:
Create Date: 2024-07-02 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'init_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_configs',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('master_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('system_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('notification_channel_id', sa.BigInteger(), nullable=True),
    sa.Column('main_language', sa.Text(), server_default='en', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guild_configs_id'), 'guild_configs', ['id'], unique=True) # ID гильдии должен быть уникальным
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guild_configs_id'), table_name='guild_configs')
    op.drop_table('guild_configs')
    # ### end Alembic commands ###
